apex/check_tc_course_id.txt, cumulusci.yml
=> Added check_tc_course_id Apex script and added package to v3.9 upgrade plan

apex/check_tc_course_id.txt
=> Fixed check_tc_course_id script

apex/check_tc_course_id.txt
=> Used custom extension to show custom error message in check_tc_course_id

apex/check_tc_course_id.txt
=> Fixed typo in check_tc_course_id

apex/check_tc_course_id.txt
=> Fixed check_tc_course_id

cumulusci.yml
=> Updated EDA pre-flight check

apex/check_tc_course_id.txt
=> Check for presence of Approved Course field in check_tc_course_id script

apex/check_tc_course_id.txt
=> check_tc_course_id fix

apex/check_tc_course_id.txt
=> Fix for check_tc_course_id

cumulusci.yml
=> Added v3.11.9

cumulusci.yml
=> Added v3.13

apex/check_tc_course_id.txt
=> Fixed bug in check_tc_course_id task

apex/check_tc_course_id.txt
=> Converted check_tc_course_id queries to COUNT queries

cumulusci.yml
=> Added LWS pre-install check to v3.13 upgrade

cumulusci.yml
=> Added v3.11.10

cumulusci.yml
=> added v3.13.2

unpackaged/post/v3.14/v3.14_03_layout/package.xml
=> Added missing layout to package.xml

unpackaged/post/v3.14/v3.14_03_layout/layouts/rio_ed__Study_Registration__c-rio_ed__RIOEducation Community Registration Layout.layout
=> Added namespace to fields in new layout

unpackaged/post/v3.14/v3.14_04_studentprofile_layoutassignment/profiles/REDU - Student.profile
=> Fixed layout assignment

cumulusci.yml
=> Added v3.13.3 and v3.14.2

cumulusci.yml
=> Added v3.14.3 to upgrade installer

cumulusci.yml
=> Added v3.14.4

cumulusci.yml
=> Added v3.15.1

cumulusci.yml
=> Added v3.15.2

cumulusci.yml
=> Removed v3.15.2

cumulusci.yml
=> Added v3.18 upgrade plan

cumulusci.yml
=> Added v3.15.3

cumulusci.yml, metadeploy/labels_en.json
=> V3.19.1-V3.18.7-V3.15.7
